backend:
  name: github
  repo: vstanyshevskyy/vpershe
  branch: main

media_folder: "static/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: articles
    label: Статті
    folder: "content/content"
    filter: {field: "contentType", value: "articles"}
    create: true
    fields:
      - {label: "Type", name: "contentType", widget: "hidden", default: "articles"}
      - {label: "Url", name: "path", widget: "string"}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Підзаголовок", name: "subtitle", widget: "string"}
      - {label: "Фото", name: "image", widget: "image", required: false}
      - {label: "Фото ALT", name: "image_alt", widget: "string", required: false}
      - {label: "Додати до каруселі на головній", name: "carousel_featured", widget: "boolean", required: false}
      - {label: "Фото для каруселі на головній (170*170)", name: "carousel_image", widget: "image", required: false}
      - {label: "Фото для каруселі ALT", name: "carousel_image_alt", widget: "string", required: false}
      - {label: "Фото для списку (250*250)", name: "list_image_articles", widget: "image", required: false}
      - {label: "Фото для списку (533*332)", name: "list_image", widget: "image", required: false}
      - {label: "Фото для списку ALT", name: "list_image_alt", widget: "string", required: false}
      - label: "Теги"
        name: "tags"
        widget: "list"    
        default: [] 
      - label: "Цікаве для тебе"
        name: "related_sidebar"
        widget: "list"
        required: false
        fields:
          - {widget: "relation", label: 'URL', hint: 'Шукай за назвою', name: 'path', collection: "content", searchFields: ["title"], displayFields: ["title", "contentType"], valueField: "path"}
      - label: "Схожі матеріали"
        name: "related_bottom"
        widget: "list"
        required: false
        fields:
          - {widget: "relation", label: 'URL', hint: 'Шукай за назвою', name: 'path', collection: "content", searchFields: ["title"], displayFields: ["title", "contentType"], valueField: "path"}
      - {label: "Текст", name: "body", widget: "markdown"}
      - {label: "Час публікації", name: "publishTime", required: false, widget: "datetime"}
      - {label: "Meta Keywords", name: "metaKeywords", widget: "string", required: false}
      - {label: "Meta Description", name: "metaDescription", widget: "string", required: false}
  - name: stories
    label: Історії
    folder: "content/content"
    filter: {field: "contentType", value: "stories"}
    create: true
    fields:
      - {label: "Type", name: "contentType", widget: "hidden", default: "stories"}
      - {label: "Url", name: "path", widget: "string"}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Підзаголовок", name: "subtitle", widget: "string"}
      - {label: "Фото", name: "image", widget: "image", required: false}
      - {label: "Фото ALT", name: "image_alt", widget: "string", required: false}
      - {label: "Додати до каруселі на головній", name: "carousel_featured", widget: "boolean", required: false}
      - {label: "Фото для каруселі на головній (170*170)", name: "carousel_image", widget: "image", required: false}
      - {label: "Фото для каруселі ALT", name: "carousel_image_alt", widget: "string", required: false}
      - {label: "Фото для списку (250*250)", name: "list_image", widget: "image", required: false}
      - {label: "Фото для списку ALT", name: "list_image_alt", widget: "string", required: false}
      - label: "Теги"
        name: "tags"
        widget: "list"    
        default: [] 
      - label: "Цікаве для тебе"
        name: "related_sidebar"
        widget: "list"
        required: false
        fields:
          - {widget: "relation", label: 'URL', hint: 'Шукай за назвою', name: 'path', collection: "content", searchFields: ["title"], displayFields: ["title", "contentType"], valueField: "path"}
      - label: "Схожі матеріали"
        name: "related_bottom"
        widget: "list"
        required: false
        fields:
          - {widget: "relation", label: 'URL', hint: 'Шукай за назвою', name: 'path', collection: "content", searchFields: ["title"], displayFields: ["title", "contentType"], valueField: "path"}
      - {label: "Текст", name: "body", widget: "markdown"}
      - {label: "Час публікації", name: "publishTime", required: false, widget: "datetime"}
      - {label: "Meta Keywords", name: "metaKeywords", widget: "string", required: false}
      - {label: "Meta Description", name: "metaDescription", widget: "string", required: false}
  - name: sexoteca
    label: Сексотека
    folder: "content/content"
    filter: {field: "contentType", value: "sexoteca"}
    create: true
    fields:
      - {label: "Type", name: "contentType", widget: "hidden", default: "sexoteca"}
      - {label: "Url", name: "path", widget: "string"}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Підзаголовок", name: "subtitle", widget: "string"}
      - {label: "Фото", name: "image", widget: "image", required: false}
      - {label: "Фото ALT", name: "image_alt", widget: "string", required: false}
      - {label: "Додати до каруселі на головній", name: "carousel_featured", widget: "boolean", required: false}
      - {label: "Фото для каруселі на головній (170*170)", name: "carousel_image", widget: "image", required: false}
      - {label: "Фото для каруселі ALT", name: "carousel_image_alt", widget: "string", required: false}
      - {label: "Фото для списку (250*250)", name: "list_image", widget: "image", required: false}
      - {label: "Фото для списку ALT", name: "list_image_alt", widget: "string", required: false}
      - label: "Теги"
        name: "tags"
        widget: "list"    
        default: [] 
      - label: "Цікаве для тебе"
        name: "related_sidebar"
        widget: "list"
        required: false
        fields:
          - {widget: "relation", label: 'URL', hint: 'Шукай за назвою', name: 'path', collection: "content", searchFields: ["title"], displayFields: ["title", "contentType"], valueField: "path"}
      - label: "Схожі матеріали"
        name: "related_bottom"
        widget: "list"
        required: false
        fields:
          - {widget: "relation", label: 'URL', hint: 'Шукай за назвою', name: 'path', collection: "content", searchFields: ["title"], displayFields: ["title", "contentType"], valueField: "path"}
      - {label: "Текст", name: "body", widget: "markdown"}
      - {label: "Час публікації", name: "publishTime", required: false, widget: "datetime"}
      - {label: "Meta Keywords", name: "metaKeywords", widget: "string", required: false}
      - {label: "Meta Description", name: "metaDescription", widget: "string", required: false}
  - name: pages
    label: Інші сторінки
    folder: "content/pages"
    create: true
    fields:
      - {label: "Type", name: "contentType", widget: "hidden", default: "pages"}
      - {label: "Url", name: "path", widget: "string"}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Підзаголовок", name: "subtitle", widget: "string"}
      - {label: "Фото", name: "image", widget: "image", required: false}
      - {label: "Фото ALT", name: "image_alt", widget: "string", required: false}
      - {label: "Додати до каруселі на головній", name: "carousel_featured", widget: "boolean", required: false}
      - {label: "Фото для каруселі на головній (170*170)", name: "carousel_image", widget: "image", required: false}
      - {label: "Фото для каруселі ALT", name: "carousel_image_alt", widget: "string", required: false}
      - {label: "Текст", name: "body", widget: "markdown"}
      - {label: "Час публікації", name: "publishTime", required: false, widget: "datetime"}
      - {label: "Meta Keywords", name: "metaKeywords", widget: "string", required: false}
      - {label: "Meta Description", name: "metaDescription", widget: "string", required: false}
  - name: advice
    label: Поради
    folder: "content/advice"
    create: true
    fields:
      - {label: "Type", name: "contentType", widget: "hidden", default: "advice"}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Url", name: "url", widget: "string"}
      - {label: "Текст", name: "body", widget: "markdown"}
      - label: "Теги"
        name: "tags"
        widget: "list"    
        default: [] 
      - {label: "Час публікації", name: "publishTime", required: false, widget: "datetime"}
  - name: settings
    label: Налаштування
    files:
      - label: 'Загальні'
        name: 'general'
        file: 'content/settings/general.md'
        fields:
          - name: 'contentType'
            widget: 'hidden'
            default: 'general_settings'
          - label: 'favicon'
            name: 'favicon'
            widget: image
          - label: 'URL сайту'
            name: 'url'
            widget: string
          - label: 'Назва організації, від імені якої постимо контент'
            name: 'organizationTitle'
            widget: string
          - label: 'Автор по замовчуванню'
            name: 'defaultAuthor'
            widget: string
          - label: 'Фото автора по замовчуванню'
            name: 'defaultAuthorImage'
            widget: image
          - label: 'Title Template'
            name: 'titleTemplate'
            widget: string
          - label: 'Title (Текст заголовку вікна браузера на головній)'
            name: 'title'
            widget: string
          - label: 'Meta Description'
            name: 'metaDescription'
            widget: string
          - label: 'Meta Keywords'
            name: 'metaKeywords'
            widget: string
          - label: 'FB Title (цей текст показуватиме ФБ при шерінгу сторінки)'
            name: 'fbTitle'
            widget: string
          - label: 'FB Description'
            name: 'fbDescription'
            widget: string
          - label: 'FB Image'
            name: 'fbImage'
            widget: image
      - label: 'Головна сторінка'
        name: 'homepage'
        file: 'content/settings/homepage.md'
        fields:
          - name: 'contentType'
            widget: 'hidden'
            default: 'homepage_settings'
          - label: 'Про проект'
            name: 'body'
            widget: 'markdown'
      - label: 'Статті'
        name: 'articles'
        file: 'content/settings/articles.md'
        fields:
          - name: 'contentType'
            widget: 'hidden'
            default: 'articles_settings'
          - label: 'Page Title'
            name: 'title'
            widget: 'string'
          - label: 'Meta Description'
            name: 'metaDescription'
            widget: string
          - label: 'Meta Keywords'
            name: 'metaKeywords'
            widget: string
          - label: 'Tag Page Title'
            name: 'tags_title'
            widget: 'string'
          - label: 'Tags Meta Description'
            name: 'tags_metaDescription'
            widget: string
          - label: 'Tags Meta Keywords'
            name: 'tags_metaKeywords'
            widget: string
      - label: 'Сексотека'
        name: 'sexoteca'
        file: 'content/settings/sexoteca.md'
        fields:
          - name: 'contentType'
            widget: 'hidden'
            default: 'sexoteca_settings'
          - label: 'Page Title'
            name: 'title'
            widget: 'string'
          - label: 'Meta Description'
            name: 'metaDescription'
            widget: string
          - label: 'Meta Keywords'
            name: 'metaKeywords'
            widget: string
          - label: 'Tag Page Title'
            name: 'tags_title'
            widget: 'string'
          - label: 'Tags Meta Description'
            name: 'tags_metaDescription'
            widget: string
          - label: 'Tags Meta Keywords'
            name: 'tags_metaKeywords'
            widget: string
      - label: 'Історії'
        name: 'stories'
        file: 'content/settings/stories.md'
        fields:
          - name: 'contentType'
            widget: 'hidden'
            default: 'stories_settings'
          - label: 'Page Title'
            name: 'title'
            widget: 'string'
          - label: 'Meta Description'
            name: 'metaDescription'
            widget: string
          - label: 'Meta Keywords'
            name: 'metaKeywords'
            widget: string
          - label: 'Tag Page Title'
            name: 'tags_title'
            widget: 'string'
          - label: 'Tags Meta Description'
            name: 'tags_metaDescription'
            widget: string
          - label: 'Tags Meta Keywords'
            name: 'tags_metaKeywords'
            widget: string
      - label: 'Поради'
        name: 'advice'
        file: 'content/settings/advice.md'
        fields:
          - name: 'contentType'
            widget: 'hidden'
            default: 'stories_settings'
          - label: 'Page Title'
            name: 'title'
            widget: 'string'
          - label: 'Meta Description'
            name: 'metaDescription'
            widget: string
          - label: 'Meta Keywords'
            name: 'metaKeywords'
            widget: string
          - label: 'Tag Page Title'
            name: 'tags_title'
            widget: 'string'
          - label: 'Tags Meta Description'
            name: 'tags_metaDescription'
            widget: string
          - label: 'Tags Meta Keywords'
            name: 'tags_metaKeywords'
            widget: string
      - label: 'Підписка на новини'
        name: 'subscribe_form_settings'
        file: 'content/settings/subscribe_form.md'
        fields:
          - name: 'contentType'
            widget: 'hidden'
            default: 'subscribe_form_settings'
          - label: 'Заголовок'
            name: 'title'
            widget: 'string'
          - label: 'email placeholder'
            name: 'email_placeholder'
            widget: string
          - label: 'Опис поля email'
            name: 'email_label'
            widget: string
          - label: 'Текст на кнопці'
            name: 'button_text'
            widget: string
          - label: 'Заголовок подяки'
            name: 'thanks_title'
            widget: string
          - label: 'Текст подяки'
            name: 'thanks_text'
            widget: string
      - label: 'Ask Box'
        name: 'ask_box_settings'
        file: 'content/settings/ask_box.md'
        fields:
          - name: 'contentType'
            widget: 'hidden'
            default: 'ask_box_settings'
          - label: 'Текст на кнопці-відкривашці'
            name: 'toggleButtonText'
            widget: 'string'
          - label: 'Текст на початку форми'
            name: 'formInstructions'
            widget: 'string'
          - label: 'Email Label'
            name: 'emailLabel'
            widget: 'string'
          - label: 'Текст згоди'
            name: 'allowToShareLabel'
            widget: 'string'
          - label: 'Згоден'
            name: 'yesLabel'
            widget: 'string'
          - label: 'Не згоден'
            name: 'noLabel'
            widget: 'string'
          - label: 'Question area label'
            name: 'questionAreaLabel'
            widget: 'string'
          - label: 'Текст кнопки відправити'
            name: 'submitButtonText'
            widget: string
          - label: 'Заголовок подяки'
            name: 'thanksTitle'
            widget: string
          - label: 'Текст подяки, якщо погодились на поширення'
            name: 'thanksTextAllowedToShare'
            widget: string
          - label: 'Текст подяки, якщо НЕ погодились на поширення'
            name: 'thanksTextNotAllowedToShare'
            widget: string
      - label: "Футер"
        name: "footer"
        file: "content/settings/footer.md"
        fields:
          - name: "contentType"
            widget: "hidden"
            default: "footer_settings"
          - label: "Копірайт"
            name: "copyrightText"
            widget: "string"
          - label: "Посилання в самом у низу"
            name: "bottomLinks"
            widget: "list"
            fields:
              - {label: Текст, name: text, widget: string, default: ""}
              - {label: URL, name: url, widget: string, default: ""}
      - label: "Навігація"
        name: "navbar"
        file: "content/settings/navbar.md"
        fields:
          - name: "contentType"
            widget: "hidden"
            default: "navbar_settings"
          - label: "Меню"
            name: "links"
            widget: "list"
            fields:
              - label: "Текст"
                name: "text"
                widget: "string"
              - label: "Посилання"
                name: "url"
                widget: "string"
          - label: "Соцмережі"
            name: "socialIcons"
            widget: "list"
            fields:
              - label: "Мережа"
                name: "type"
                widget: "select"
                options: ["Facebook", "Twitter", "Instagram", "Google"]
              - label: "Посилання"
                name: "url"
                widget: "string"
  - name: content
    label: Весь контент - краще не чіпати
    folder: "content/content"
    create: false
    fields:
      - {label: "Type", name: "contentType", widget: "hidden", default: "articles"}
      - {label: "Url", name: "path", widget: "string"}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Підзаголовок", name: "subtitle", widget: "string"}